// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9t21S_bvSINgoyEfHP-XX5o1pAmadGVE',
    appId: '1:34542936315:web:48f2fe2dc4c0f7a36e505e',
    messagingSenderId: '34542936315',
    projectId: 'iti-project-26abf',
    authDomain: 'iti-project-26abf.firebaseapp.com',
    storageBucket: 'iti-project-26abf.appspot.com',
    measurementId: 'G-92J0HR90VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEwncz5qG1iH9fAHmGdDvbNufvHbrk0to',
    appId: '1:34542936315:android:10da2171e939d8ce6e505e',
    messagingSenderId: '34542936315',
    projectId: 'iti-project-26abf',
    storageBucket: 'iti-project-26abf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9iLmkhr534i3bvFFaTRCDm8Ezmuc7xI',
    appId: '1:34542936315:ios:b5f454f8332fbbe76e505e',
    messagingSenderId: '34542936315',
    projectId: 'iti-project-26abf',
    storageBucket: 'iti-project-26abf.appspot.com',
    iosClientId: '34542936315-v0hr18a1lmh02k1k5jd880d1bhdvcbu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.welcome',
  );
}
